title: Christoph Senn, PhD
url: "https://delpart.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "titech-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/delpart"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
    link: "/assets/cv/cv_senn_christoph.pdf"
 - name: "Contact"
   link: "contact"
