title: Christoph Senn - PhD Candidate
url: "https://delpart.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "titech-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/delpart"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
